This document describes the features of the next major version of Szó.


== Hierarchical tags

Tag may belong to groups. With `@Foo/Bar` and `@Foo/Baz` somewhere, infer a tag group:

----
[ ] Foo
[ ]   Bar
[ ]   Baz
----



== Link to Wiktionary

Links to Wiktionary only appear in a card detail.

Many words do appear on Wiktionary, http://hu.wiktionary.org/wiki/szilva[through] http://en.wiktionary.org/wiki/szilva[various] http://fr.wiktionary.org/wiki/szilva[languages]. It turns out that French is the most incomplete. The Hungarian is probably the best average choice.

A link validity check makes the link to Wiktionary appear if valid.

This is an option, disabled by default for saving queries on a mobile device.

Because of potential high number of cards, there is no check until the card detail appears. The check occurs in background using `XmlHttpRequest` but not in the Worker, which would make the update difficult.

There is a map for every card telling if the check did occur, and its success. Even better: use browser's local storage to keep this on the long term.


Recent finding:
http://szotar.sztaki.hu/search?fromlang=hun&tolang=fre
Really good dictionary. Magyar-English is more furnished, though.

Because online dictionaries don't all return a 404 (sztaki.hu doesn't) we need to use dictionary-specific logic. The solution is to hardcode all of that logic in a map. Then the vocabulary file choses to activate those dictionaries.




== Support mobile devices

There is no intent to develop a mobile app, mobile support occurs only through HTML and JavaScript.

Loading the whole application from a website it acceptable, but what about the offline mode? Should we store something? Luckily the http://www.thecssninja.com/javascript/how-to-create-offline-webapps-on-the-iphone[offline mode] exists, thanks to http://appcachefacts.info[caching] .

A nice mobile-specific feature would be an "invert color" to support dark background.

There are tons of crappy vocabulary-learning apps. Among the less stupid:

* http://www.appolicious.com/education/apps/497630-vocab-junkie-bold-learning-solutions-inc[Vocab Junkie]
* http://itunes.apple.com/fr/app/vocabulary-trainer/id436103462[Vocabulary Trainer]
* http://itunes.apple.com/fr/app/vocabulary-trainer-english/id377911662[Vocabulary Trainer: English - Hungarian]

Vocab Pro HD mentions the http://itunes.apple.com/fr/app/vocab-pro-hd/id497950298[ProVoc File Format] .
ProVoc is a binary format, so it is not easy as Szó. And it seems abandoned.




== Multilingual user interface

Would look serious while this doesn't seem to be such important.

Use http://en.wikipedia.org/wiki/ISO_639-2[ISO 639-2/T] codes internally:

* hun : Hungarian "Magyar"
* fra : French "Français"
* eng : English "English"



== Typographic tricks

Replace `_` by non-breakable space at rendering time.



== Print enhancements

Insert URL (along with current content-aware URL) as a QR code.

There are means to generate QR codes http://jeromeetienne.github.com/jquery-qrcode[offline with JavaScript].


== Still no stats

Stats are a bottomless hole for development and make people stupid.


== Summary of controls

Top-level buttons:

* All
* None
* Next
* Add to Deck/Remove from Deck
* List view/Card view
* Invert

Settings:

* Skin (day, night)
* Wiktionary links (yes, no)
* Button to clear Wiktionary link cache.
* Language (French, English, Hungarian)



== Chrome integration

Chrome Apps http://developer.chrome.com/trunk/apps/app_deprecated.html[forbid] access to Browser history. So Chrome Apps aren't what we need.

What we need: some Chrome Extension that can read the files in a user-specified directory.

There is an API for http://stackoverflow.com/a/7645775/1923328[that] but only for files under Extension's root directory.

https://developer.chrome.com/extensions/npapi.html[NPAPI] plugins seem too much permissive.

HTML 5 http://www.html5rocks.com/en/tutorials/file/dndfiles[manual selection] could do the job if there are not too many files (can't select a whole directory, need to pick files one by one).

Clever guy already found that: http://jorgecardoso.eu/htmlblog/2012-08-30-Listing%20a%20user%20directory%20with%20javascript%20in%20a%20Chrome%20extension.html[Listing a user directory with javascript in a Chrome extension]



== Eye candy

=== Checkbox tree

The ultimate (GPL-licensed):
https://code.google.com/p/dynatree

Sample of partial checked checkboxes:
http://wwwendt.de/tech/dynatree/doc/sample-select.html#tree3

Dynatree-1.2.4 behaves well with JQuery-1.9.

Minified version weights 45 kb.


=== Animating

Somebody showed me the "word fishing" with various words in the foreign language falling down the screen. You pick those that you don't know.

Nice library for fluid translation + rotation:
http://www.jstween.org



== Glossary

"Equivalence" sucks.

The real word for a dictionary entry seems to be "entry" (at least in a hardcover Harrap's Shorter) which is "article" in French.

"Card" is not so bad.

Wikipedia/Wiktionary use "article".

How to describe the line-column system inside an "entry"?

A Pack represents a file containing a list of Cards, and reading/parsing errors.

The whole set of Cards and Packs is a Vocabulary.


