*Szótárgép* means "vocabulary machine" in Magyar (Hungarian). It is a standalone application for learning Magyar from French. You should pronounce it "soo-taarrr-gééép" with long vowels and "r" tapped like in Spanish.

It's a small piece of HTML and JavaScript, essentially using JQuery. Vocabulary files are text files that anybody can edit.


=== Installation

To install Szótárgép, download the latest version from https://github.com/caillette/szotargep (click on the "Download" button). Unzip it somewhere and open the `vocabulary.html` file in a Web browser.


=== Usage

Check the vocabulary files and click on "Disclose" ("Felfel") button to see the translation. Hitting the "Enter" key produces the same effect.

A pair of termes is an _equivalence_. To see the list of all checked equivalences, check "List" ("Lista").


=== Adding or editing vocabulary files

Create some plain text file with a decent text editor like http://notepad-plus-plus.org[NotepadPlusPlus] and take care of chosing UTF-8 encoding.

There must be a blank line at the start and at the end of the file.

An equivalence contains at least two terms, on two adjacent lines. Under each term, there can be any number of additional definitions that start with at least one space character. Additional definitions for the first language will disclose one by one.

To reference a new vocabulary file, edit `vocabulary.html` and add one `<dl>` entry. Then refresh the page in the Web browser.

See existing files for examples.


=== Supported configurations

* Safari 5.1 on Mac OS X 10.6.8: works fine.
* Firefox 6.0 on Mac OS X 10.6.8: works fine. Doesn't support printing more than one page.
* Chrome 13 on Mac OS X 10.6.8: works fine with the special option described below.

Szótárgép uses very standard DHTML features so it's likely to run on Firefox with other operating systems.

There will be no effort to make Szótárgép run on any version of Internet Explorer.


==== Running with Chrome

To say things simply, Chrome forbids access to the local filesystem by default. To circumvent this, launch Chrome like this:

.Mac OS X
  $ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --allow-file-access-from-files

.Windows
  > chrome.exe --allow-file-access-from-files



=== License

Szótárgép HTML and JavaScript code are released under *GNU Public License Version 3*.

Vocabulary files are released under *Creative Commons Attribution-ShareAlike 3.0 license*. "This license lets others remix, tweak, and build upon your work even for commercial purposes, as long as they credit you and license their new creations under the identical terms."

Other libraries are subject to their original licenses:

* JQuery comes with a dual license: MIT or GPL Version 2.
* The keyboard shortcuts library is under BSD license, which probably requires a mention of its author, Binny V. A.




