*Szótárgép* means "vocabulary machine" in Magyar (Hungarian). It is a standalone application for learning Magyar from French. You should pronounce it "so-o-taarrr-géép" with long vowels and "r" tapped like in Spanish, and the accent on the beginning of the word.

Starting from a customizable vocabulary list, it choses random terms in one language, and discloses the translation at user's demand. There is also a list view with all the terms, and a switch between prose and translation.

Szótárgép is a small piece of HTML and JavaScript, essentially using JQuery. Vocabulary files are text files that anybody can edit.


=== Installation

To install Szótárgép, download the latest version from https://github.com/caillette/szotargep/zipball/master and unzip it somewhere and open the `szotargep.html` file in a Web browser (see "Supported configurations" below).


=== Usage

Check the vocabulary files and click on "Disclose" ("Felfel") button to see the translation. Hitting the "Enter" key produces the same effect.

To see the list of all terms in checked files, check "List" ("Lista").


=== Adding or editing vocabulary files

Create some plain text file with a decent text editor like http://notepad-plus-plus.org[NotepadPlusPlus] and take care of chosing UTF-8 encoding. Do not use Window's Notepad, which messes the encoding up.

An optional `title: [nicer title]` may override the filename for nicer display.

There must be a blank line before and after each term pair.

A term pair is made of groups of lines (at least two lines, one for the original and one line for the translation). Under each term, there can be any number of additional definitions that start with at least one space character. Additional definitions for the first language will disclose one by one.

Only term pairs with valid characters will show. Any non-recognized character will cause the term pair to not show.

Here is a sample of vocabulary file containing a title and two term pairs. Don't forget there is an empty line at the end.

----
  title: Sok szók!

  plaire
    à quelqu'un
  tetsik
    ~vkik
    tetszett, tetsszen, tetszene

  après, ensuite
  majd

----

To reference a new vocabulary file, edit `szotargep.html` and add one `<dl>` entry. Then refresh the page in the Web browser.

See existing files for examples.


=== Using with other languages

Szótárgép may be useful for learning other languages.

As it reads UTF-8 vocabulary files, Szótárgép accomodates with most of character sets, but it doesn't support right-to-left writing.


=== Supported configurations

* Safari 5.1 on Mac OS X 10.6.8: works fine.
* Firefox 6.0 on Mac OS X 10.6.8: works fine.
* Chrome 13 on Mac OS X 10.6.8: doesn't work.

Szótárgép should work on Windows and Linux as well, using the same version of Firefox or Safari. Szótárgép might work on other configurations as well. There will be no effort to make Szótárgép run on any version of Internet Explorer.


==== The Chrome problem

(In simple words) Chrome forbids access to the local filesystem by default. Yes there is the `--allow-file-access-from-files` command line option, that opens access to your filesystem to every other Web page, so don't use it, period.


=== License

Szótárgép HTML and JavaScript code are released under *GNU Public License Version 3*.

Vocabulary files are released under *Creative Commons Attribution-ShareAlike 3.0 license*. "This license lets others remix, tweak, and build upon your work even for commercial purposes, as long as they credit you and license their new creations under the identical terms."

Other libraries are subject to their original licenses:

* JQuery and its plugins come with a dual license: MIT or GPL Version 2.
* The keyboard shortcuts library is under BSD license, which probably requires a mention of its author, Binny V. A.




